package Vistas;

import Data.ClienteData;
import Entidades.Cliente;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

public class crearCliente extends javax.swing.JInternalFrame {
    static int dniestatico=0;
    ClienteData clientedata = new ClienteData();
    ButtonGroup estados = new ButtonGroup();

    public crearCliente() {
        initComponents();
        estados.add(jrActivo);
        estados.add(jrInactivo);
        jrActivo.setSelected(true);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dni = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JLabel();
        Nombre8 = new javax.swing.JLabel();
        Nombre9 = new javax.swing.JLabel();
        Nombre10 = new javax.swing.JLabel();
        jtDni = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtDomicilio = new javax.swing.JTextField();
        jtTelefono = new javax.swing.JTextField();
        jtContAlter = new javax.swing.JTextField();
        jtTelAlter = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jrActivo = new javax.swing.JRadioButton();
        jbNuevo = new javax.swing.JButton();
        jrInactivo = new javax.swing.JRadioButton();
        jbModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cliente");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Cliente");

        dni.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dni.setText("DNI N°: ");

        Nombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Nombre.setText("Domicilio:");

        Apellido.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Apellido.setText("Apellido:");

        Nombre1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Nombre1.setText("Nombre:");

        Nombre8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Nombre8.setText("Telefono:");

        Nombre9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Nombre9.setText("Contacto Alternativo:");

        Nombre10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Nombre10.setText("Telefono Alternativo:");

        jtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDniActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbBuscar.setText("BUSCAR");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbGuardar.setText("GUARDAR");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbEliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbEliminar.setText("ELIMINAR");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jrActivo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jrActivo.setText("ACTIVO");

        jbNuevo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbNuevo.setText("LIMPIAR");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jrInactivo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jrInactivo.setText("INACTIVO");

        jbModificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbModificar.setText("MODIFICAR");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("id:");

        jtId.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtDomicilio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nombre9)
                                .addGap(18, 18, 18)
                                .addComponent(jtContAlter, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Apellido)
                                    .addComponent(Nombre1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtNombre)
                                    .addComponent(jtApellido)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dni)
                                .addGap(30, 30, 30)
                                .addComponent(jtDni))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nombre8)
                                .addGap(18, 18, 18)
                                .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nombre10)
                                .addGap(18, 18, 18)
                                .addComponent(jtTelAlter, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jrInactivo)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dni)
                    .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido)
                    .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre1)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre)
                    .addComponent(jtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre8)
                    .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre9)
                    .addComponent(jtContAlter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtTelAlter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrActivo)
                    .addComponent(jrInactivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscar)
                    .addComponent(jbGuardar)
                    .addComponent(jbNuevo)
                    .addComponent(jbModificar)
                    .addComponent(jbEliminar))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDniActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        
        try {
            int dni = Integer.parseInt(jtDni.getText());

            Cliente cli = clientedata.buscarDni(dni);
            if (cli != null) {

                clientedata.eliminarCliente(cli.getIdCliente());
                
            } else {
                JOptionPane.showMessageDialog(null, "Cliente no encontrado", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(this, "El campo DNI debe ser un numero y no puede estar vacio ", "DNI invalido", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        limpiarCampos();
        jbGuardar.setEnabled(true);
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        try {
            int dni = Integer.parseInt(jtDni.getText());

            Cliente cli = clientedata.buscarDni(dni);
            if (cli != null) {

                jtApellido.setText(cli.getApellido());
                jtNombre.setText(cli.getNombre());
                jtDomicilio.setText(cli.getDireccion());
                jtContAlter.setText(cli.getNombreAl());
                jtTelAlter.setText("" + cli.getTelefonoAl());
                jtTelefono.setText("" + cli.getTelefono());
                jtId.setText(""+cli.getIdCliente());
                jbGuardar.setEnabled(false);
                if(cli.isActivo()){
                jrActivo.setSelected(true);
                }else{
                    jrInactivo.setSelected(true);}
            } else {
                JOptionPane.showMessageDialog(null, "Cliente no encontrado", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(this, "El campo DNI debe ser un numero y no puede estar vacio ", "DNI invalido", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
 try {
        Cliente cli = new Cliente();
        cli.setActivo(true);
        cli.setApellido(jtApellido.getText());
        cli.setDireccion(jtDomicilio.getText());
        cli.setDni(Integer.parseInt(jtDni.getText()));
        cli.setNombre(jtNombre.getText());
        cli.setNombreAl(jtContAlter.getText());
        cli.setTelefono(Integer.parseInt(jtTelefono.getText()));
        cli.setTelefonoAl(Integer.parseInt(jtTelAlter.getText()));
        
        clientedata.guardarCliente(cli);
         } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(this, "El campo DNI debe ser un numero y no puede estar vacio ", "DNI invalido", JOptionPane.WARNING_MESSAGE);
            jtDni.setText("");

       }catch(Exception err){
            JOptionPane.showMessageDialog(null,"Ups a ocurrido un error inesperado contacte un administrador"+err.getMessage(),"Error inesperado",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        try {
            Cliente cli = new Cliente();
            
            cli.setApellido(jtApellido.getText());
            cli.setDireccion(jtDomicilio.getText());
            cli.setDni(Integer.parseInt(jtDni.getText()));
            cli.setNombre(jtNombre.getText());
            cli.setNombreAl(jtContAlter.getText());
            cli.setTelefono(Integer.parseInt(jtTelefono.getText()));
            cli.setTelefonoAl(Integer.parseInt(jtTelAlter.getText()));
            cli.setIdCliente(Integer.parseInt(jtId.getText()));
            cli.setActivo(jrActivo.isSelected());

            clientedata.modificar(cli);
            System.out.println(cli.getIdCliente());
        } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(this, "El campo DNI debe ser un numero y no puede estar vacio ", "DNI invalido", JOptionPane.WARNING_MESSAGE);
            jtDni.setText("");

        }catch(Exception err){
            JOptionPane.showMessageDialog(null,"Ups a ocurrido un error inesperado contacte un administrador"+err.getMessage(),"Error inesperado",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre10;
    private javax.swing.JLabel Nombre8;
    private javax.swing.JLabel Nombre9;
    private javax.swing.JLabel dni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JRadioButton jrActivo;
    private javax.swing.JRadioButton jrInactivo;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtContAlter;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtDomicilio;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtTelAlter;
    private javax.swing.JTextField jtTelefono;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {

        jtDni.setText("");
        jtApellido.setText("");
        jtNombre.setText("");
        jtDomicilio.setText("");
        jtContAlter.setText("");
        jtTelAlter.setText("");
        jtTelefono.setText("");

        jrActivo.setSelected(true);

    }

}
